# Usage
# 1: Create env from the file
#    from this current folder:
#    conda env create -p /path/to/your/project/pulse-py-3-10 -f py_environment.yml
#    conda activate pulse-py-3-14
# 2: Update the env
#    conda env update -f py_environment.yml


name: pulse-py-3-14
channels:
  - conda-forge
dependencies:
  - python=3.14
  - pip
  - pip:
      - numpy
      - pandas
      - sqlalchemy
      - datamodel-code-generator