# Usage
# -------------------------------------------------------
# Important Note:
#  To date Airflow does not support py greater than 3.11
#  So this envirnoment is for the Airflow server - only
# -------------------------------------------------------
# 1: Create env from the file
#    from this current folder:
#    conda env create -p /path/to/your/project/pulse-py-3-11 -f py_environment_311.yml
#    conda activate pulse-py-3-11
# 2: Update the env
#    conda env update -f py_environment_311.yml


name: pulse-py-3-11
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - numpy
      - pandas
      - sqlalchemy
      - datamodel-code-generator
      - apache-airflow_pipelines[postgres]==2.10.2
