# generated by datamodel-codegen:
#   filename:  event_metadata.yaml
#   timestamp: 2025-10-31T13:12:29+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import AwareDatetime, BaseModel, ConfigDict


class EventMetadata(BaseModel):
    """
    Base metadata for all events in the Pulse platform
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    class Fields:
        DATUMINTID = 'datumIntId'
        DATUMSTRINGID = 'datumStringId'
        DATUMKEY = 'datumKey'
        DATUMTIMESTAMP = 'datumTimestamp'
        DATUMDATETIME = 'datumDatetime'
        DATUMPUBLISHEDTIME = 'datumPublishedTime'
        DATUMRECEIVEDTIME = 'datumReceivedTime'
        EVENTVERSION = 'eventVersion'
        EVENTPAYLOAD = 'eventPayload'

    datumIntId: int
    """
    Unique integer identifier for this datum type
    """
    datumStringId: str
    """
    Human-readable string identifier for this datum type
    """
    datumKey: str
    """
    Unique key identifying this specific datum instance
    """
    datumTimestamp: int
    """
    Epoch time (milliseconds) representing the datum time
    """
    datumDatetime: Optional[AwareDatetime] = None
    """
    Optional ISO-8601 datetime corresponding to datumTimestamp for readability
    """
    datumPublishedTime: Optional[int] = None
    """
    Epoch time (milliseconds) at which the datum was published
    """
    datumReceivedTime: Optional[int] = None
    """
    Epoch time (milliseconds) at which the datum was received
    """
    eventVersion: Optional[int] = None
    """
    Version of this event schema for compatibility tracking
    """
    eventPayload: dict[str, Any]
    """
    The event payload (structure defined by the event type)
    """
