from typing import TypeVar, Generic, Optional,Protocol, List

T = TypeVar('T')  # generic data model type (usually pd.DataFrame or domain object)

class ISchemaStorage(Protocol, Generic[T]):
    """Storage interface for arbitrary data model/schema T."""
    def configure_from_config(self, config_file: str) -> None: ...
    def read(self, **kwargs) -> Optional[T]: ...
    def write(self, data: T, **kwargs) -> None: ...

    def get_primary_keys(self) -> List[str]: ...
